# Nombre de la aplicación
spring.application.name=proto

# --- CONFIGURACIÓN DE MYSQL ---
# ¡IMPORTANTE! Aquí va el nombre EXACTO de tu base de datos en Workbench
spring.datasource.url=jdbc:mysql://localhost:3306/db_adquisisciones?useSSL=false&serverTimezone=UTC

# Tu usuario de MySQL (usualmente root)
spring.datasource.username=root

# TU CONTRASEÑA DE MYSQL (La que usas para entrar a Workbench)
# Si no tienes contraseña, deja esto vacío así: spring.datasource.password=
spring.datasource.password=admin

# Driver explícito para MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 'create' borra las tablas y las crea de nuevo (Limpia la BD).
# NOTA: Cambiar a 'update' de nuevo después del primer reinicio para no perder datos.
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola (útil para depurar)
spring.jpa.show-sql=true

# Dialecto de MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# === JWT Configuration ===
jwt.secret=DGRM_SecretKey_2026_SistemaAdquisiciones_CambiameEnProduccion!!
jwt.expiration=86400000